import Head from "next/head";

function Services() {
  return (
    <>
      <Head>
        <title>| Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ fontSize: "3rem", backgroundColor: "grey" }}>
        This is Servicessssssssssss
      </div>
    </>
  );
}

export default Services;
